### ISSUE TITLE
Chap 16, cell[49], Reusing Pretrained Embeddings and Language Models.

### ISSUE THREAD

**Issue by Asjad22** [ageron/handson-ml3#27]
Hello, I'm using Nvidia Geforce 1050 ti 4gb, after running cell [49], I'm getting this error.
Kindly share the requirements of GPU which will run smoothly with this book.

W tensorflow/core/framework/op_kernel.cc:1733] RESOURCE_EXHAUSTED: failed to allocate memory

**Comment by ageron** [comment]
Hi @Asjad22 ,

Thanks for your question, and sorry for the late response.

The module is about 1GB in size (as indicated in the [model's page](https://tfhub.dev/google/universal-sentence-encoder/4)), but that's just the size of the weights: you must also have enough RAM for the activations, which depends on the batch size (defaults to 32), and since the code trains the model, the activations must be preserved throughout all layers for backprop.

I just ran the model in Colab, which allocated a T4 GPU with 16GB or RAM, and the _Runtime > Manage sessions_ page showed that 8.7GB were used:

<img width="792" alt="image" src="https://user-images.githubusercontent.com/76661/192175122-25bacb04-6828-4311-bfed-3dbb236c2f02.png">

So 4GB will definitely not be enough without changing the code. However, if you reduce the batch size, you may be able to get it to work. In `model.fit()`, try setting `batch_size=1`, just to see if it's possible. If so, then try increasing this value gradually until you find the limit.

Also, make sure you are not running any other GPU process in parallel.

Hope this helps.

**Comment by Asjad22** [comment]
Thankyou for these details.

**Comment by cfcurtis** [comment]
Hello, I'm resurrecting this closed issue as I've encountered exactly the same problem, but on Colab (free tier, T4 GPU). I kept getting a message that `Your session crashed after using all available ram` partway through the second epoch. I tried reducing the batch size to 16 and it got to the 4th epoch very slowly before telling me I've used up my free GPU runtime allotment.

I'm not sure what might have changed, and I'm afraid I can't see the logs anymore because the session was killed. I was keeping an eye on the memory and it looked like it was closer to running out of CPU ram than GPU, but I can't say for certain.

The minimal code is as follows:

```python
import tensorflow as tf
import tensorflow_datasets as tfds

raw_train_set, raw_valid_set, raw_test_set = tfds.load(
    name="imdb_reviews",
    split=["train[:90%]", "train[90%:]", "test"],
    as_supervised=True
)
BATCH_SIZE = 16
tf.random.set_seed(42)
train_set = raw_train_set.shuffle(5000, seed=42).batch(BATCH_SIZE).prefetch(1)
valid_set = raw_valid_set.batch(BATCH_SIZE).prefetch(1)
test_set = raw_test_set.batch(BATCH_SIZE).prefetch(1)
import os
import tensorflow_hub as hub

os.environ["TFHUB_CACHE_DIR"] = "my_tfhub_cache"
tf.random.set_seed(42)  # extra code – ensures reproducibility on CPU
model = tf.keras.Sequential([
    hub.KerasLayer("https://tfhub.dev/google/universal-sentence-encoder/4",
                   trainable=True, dtype=tf.string, input_shape=[]),
    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dense(1, activation="sigmoid")
])
model.compile(loss="binary_crossentropy", optimizer="nadam",
              metrics=["accuracy"])
model.fit(train_set, validation_data=valid_set, epochs=10)
```

This is as far as I got:

<img width="685" alt="image" src="https://github.com/ageron/handson-ml3/assets/282731/255cdf98-ae1b-4690-ba07-51e0e295b14d">
