### ISSUE TITLE
[BUG] homl.info/colab3 URL is down

### ISSUE THREAD

**Issue by smith558** [ageron/handson-ml3#32]
The URL from the book (https://homl.info/colab3) is down

![image](https://user-images.githubusercontent.com/44023416/206261907-c298c5a6-a0e2-44cd-953a-c1257d8bd286.png)

**Comment by ageron** [comment]
Yikes, really sorry about that, it looks like all of homl.info is down. I'm looking into it now, it should be fixed shortly.

**Comment by ageron** [comment]
Problem solved, it was really stupid: the auto-renewal of homl.info failed because my credit card was stolen a few months ago so I had to cancel it, and I forgot to provide my new credit card details to the web hosting company. They _did_ send me a few alerts, but these ended up in my "Updates" folder in Gmail, which is so full of crap that I missed them. 🤦 My apologies for the inconvenience!

**Comment by smith558** [comment]
> Problem solved, it was really stupid: the auto-renewal of homl.info failed because my credit card was stolen a few months ago so I had to cancel it, and I forgot to provide my new credit card details to the web hosting company. They _did_ send me a few alerts, but these ended up in my "Updates" folder in Gmail, which is so full of crap that I missed them. facepalm My apologies for the inconvenience!

Happens. I hope your accounts are safe and that not much else has happened!
