### ISSUE TITLE
in chapter 10 : why  input shape should be (input_shape=x_train[:1])  not in this way input_shape = x_train[1:].shape) 

### ISSUE THREAD

**Issue by atoshpulatov** [ageron/handson-ml3#33]

**Comment by ageron** [comment]
Hi @atoshpulatov ,

Thanks for your question.

The book & notebook contain `shape=X_train.shape[1:]`, not `shape=X_train[1:]`.

The `shape` argument expects the shape of each item in the dataset, not the shape of the dataset itself. That's why we need to skip the first dimension of `X_train`. In other words, that's why we use `shape=X_train.shape[1:]` instead of `shape=X_train.shape`.

Hope this helps.
