### ISSUE TITLE
[BUG] Chapter 2 cell 72: '.toarray()' missing in df_test example

### ISSUE THREAD

**Issue by Pattkopp** [ageron/handson-ml3#36]
Running cell 72 in the Chapter 2 returns a 2x5 sparse matrix and not a numpy array.
I run this in Jetbrains DataSpell.

**To Reproduce**
cell 72:
```
cat_encoder.transform(df_test)
```

Not an exception and the output is correct - it just misses the step of converting the output to a numpy array. The np array output is displayed both in the book (page 74 at the top as well as in the notebook).

```
<2x5 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>
```

**Expected behavior**
The expected output is the output in the book (p. 74) or in the notebook (out:72)
I achieve this result by adding ```.toarray()``` to the code

**Versions (please complete the following information):**
 - OS: MacOS Ventura 13.1
 - Python: 3.10
 - TensorFlow: as per requirements.txt
 - Scikit-Learn: as per requirements.txt
- Other libraries that may be connected with the issue: Using Jetbrains DataSpell

**Additional context**
![DataSpellProjects_–_homl3_ch2_ipynb](https://user-images.githubusercontent.com/7068279/210056249-6bf2ea6b-cc1d-46b2-b78d-5ef330d43c03.png)

**Comment by ageron** [comment]
Thanks for your feedback @Pattkopp .
I'm not able to reproduce this issue: I'm getting a NumPy array instead of a sparse matrix:

<img width="343" alt="image" src="https://user-images.githubusercontent.com/76661/210704486-22c7e6ef-2dbb-46ca-ae60-475ce560d8c1.png">

Note that cell #69 create a new `OneHotEncoder` with `sparse=False`, so its output really should not be sparse. Perhaps you skipped that cell? Or maybe you ran the earlier cell again which replaced the `cat_encoder` variable?

Note: in Scikit-Learn 1.2, the `sparse` argument was renamed `sparse_output`, but `sparse` will only be removed in version 1.4, and I just tested: it still works fine (except you get a deprecation warning).

**Comment by Pattkopp** [comment]
Hi @ageron and happy new year!

You are certainly right: I overlooked the `sparse=False` in cell #69. Once I add that, it produces the correct output. Apologies for raising this non-bug, I had thought I checked thoroughly but apparently not...
